name: Testing

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: gha-runner-scale-set
    container:
      image: alpine:latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Echo Message
      run: echo "Hello World"
